set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_7seg_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports xung_0]
set_property PACKAGE_PIN C15 [get_ports xung_0]
set_property PACKAGE_PIN D12 [get_ports {led_7seg_out_0[3]}]
set_property PACKAGE_PIN A11 [get_ports {led_7seg_out_0[4]}]
set_property PACKAGE_PIN B11 [get_ports {led_7seg_out_0[5]}]
set_property PACKAGE_PIN G13 [get_ports {led_7seg_out_0[6]}]
set_property PACKAGE_PIN C1 [get_ports spi_ss_io]

set_property PACKAGE_PIN E15 [get_ports {led_7seg_out_0[2]}]
set_property PACKAGE_PIN E16 [get_ports {led_7seg_out_0[1]}]
set_property PACKAGE_PIN D15 [get_ports {led_7seg_out_0[0]}]
