# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/testgame.xdc

# Block Designs: bd/Testgame/Testgame.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame || ORIG_REF_NAME==Testgame} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_microblaze_0_0/Testgame_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_microblaze_0_0 || ORIG_REF_NAME==Testgame_microblaze_0_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_dlmb_v10_0/Testgame_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_dlmb_v10_0 || ORIG_REF_NAME==Testgame_dlmb_v10_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_ilmb_v10_0/Testgame_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_ilmb_v10_0 || ORIG_REF_NAME==Testgame_ilmb_v10_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_dlmb_bram_if_cntlr_0/Testgame_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Testgame_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_ilmb_bram_if_cntlr_0/Testgame_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Testgame_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_lmb_bram_0/Testgame_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_lmb_bram_0 || ORIG_REF_NAME==Testgame_lmb_bram_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_mdm_1_0/Testgame_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_mdm_1_0 || ORIG_REF_NAME==Testgame_mdm_1_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_clk_wiz_1_0/Testgame_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_clk_wiz_1_0 || ORIG_REF_NAME==Testgame_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_rst_clk_wiz_1_100M_0/Testgame_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Testgame_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_axi_uartlite_0_0/Testgame_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_axi_uartlite_0_0 || ORIG_REF_NAME==Testgame_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_axi_quad_spi_0_0 || ORIG_REF_NAME==Testgame_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_xbar_0/Testgame_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_xbar_0 || ORIG_REF_NAME==Testgame_xbar_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_microblaze_0_axi_periph_0/Testgame_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Testgame_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_pmosip_0_1/Testgame_pmosip_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_pmosip_0_1 || ORIG_REF_NAME==Testgame_pmosip_0_1} -quiet] -quiet

# IP: bd/Testgame/ip/Testgame_axi_gpio_0_1/Testgame_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Testgame_axi_gpio_0_1 || ORIG_REF_NAME==Testgame_axi_gpio_0_1} -quiet] -quiet

# XDC: bd/Testgame/Testgame_ooc.xdc
