# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0.xci
# IP: The module: 'Testgame_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0.xci
# IP: The module: 'Testgame_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado/TTCS/TTCS.srcs/sources_1/bd/Testgame/ip/Testgame_axi_quad_spi_0_0/Testgame_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Testgame_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
