@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 14 08:45:42 +0700 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim BCD8bit_tb_behav -key {Behavioral:sim_1:Functional:BCD8bit_tb} -tclbatch BCD8bit_tb.tcl -protoinst "protoinst_files/Testgame.protoinst" -protoinst "protoinst_files/TestSPI.protoinst" -protoinst "protoinst_files/Test.protoinst" -protoinst "protoinst_files/BarrelShifter.protoinst" -protoinst "protoinst_files/TestCounterGray.protoinst" -protoinst "protoinst_files/TestCounterBinary.protoinst" -protoinst "protoinst_files/DynamicCounter.protoinst" -protoinst "protoinst_files/TestVIO.protoinst" -protoinst "protoinst_files/TestILA.protoinst" -log simulate.log"
call xsim  BCD8bit_tb_behav -key {Behavioral:sim_1:Functional:BCD8bit_tb} -tclbatch BCD8bit_tb.tcl -protoinst "protoinst_files/Testgame.protoinst" -protoinst "protoinst_files/TestSPI.protoinst" -protoinst "protoinst_files/Test.protoinst" -protoinst "protoinst_files/BarrelShifter.protoinst" -protoinst "protoinst_files/TestCounterGray.protoinst" -protoinst "protoinst_files/TestCounterBinary.protoinst" -protoinst "protoinst_files/DynamicCounter.protoinst" -protoinst "protoinst_files/TestVIO.protoinst" -protoinst "protoinst_files/TestILA.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
